### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by jdblack** [zakkor/slayrl#1]
I wandered this while searching for Ebiten projects to see what adoption is like.  I tried building and running slayrl, and got the following:

`Sat.21:21  jblack@Jamess-MBP [master]

~/test/slayrl$ ./slayrl
panic: open ./resources/tileset_zilk.png: no such file or directory

goroutine 1 [running, locked to thread]:
main.init.0()
	/Users/jblack/test/slayrl/resources.go:23 +0x2e5
Sat.21:21  jblack@Jamess-MBP [master]

~/test/slayrl$ ls ./resources/tileset_zilk.png
./resources/tileset_zilk.png
`

<img width="796" alt="Screen Shot 2022-01-22 at 9 21 44 PM" src="https://user-images.githubusercontent.com/1109549/150666076-6cf30e27-94b0-4d70-98ce-d3d86fb652c0.png">

**Comment by zakkor** [comment]
Hey there, thanks for the bug report. I upgraded the `ebiten` dependency to v2 and fixed this issue.

Press `K` to look around!
